import Foundation

/// Compile-time German→English string lookup.
///
/// Source stays in vanilla German; `#L(...)` expands at compile time to a call
/// against the runtime table in `Translations.swift` (generated by
/// `scripts/i18n-codegen.ts` from `wimg-web/src/lib/translations/en.ts`).
///
/// Usage:
///
///     Text(#L("Gesamtsaldo"))
///     Text(#L("\(count) Transaktionen"))   // interpolation → %@ placeholders
///     Label(#L("Abrufen"), systemImage: "arrow.down.doc")
///     let msg = #L("Wöchentlich")          // anywhere a String is expected
///
/// For dynamic strings (e.g. `category.name` from the model layer), use the
/// plain function `L(_:)` defined below — same lookup, no compile-time
/// extraction.
@freestanding(expression)
public macro L(_ key: String) -> String =
    #externalMacro(module: "WimgI18nMacros", type: "LocalizedMacro")

/// Runtime translation function for non-literal arguments.
@inlinable
public func L(_ key: String) -> String { __t(key) }

/// Runtime lookup. Reads `wimg_locale` from `UserDefaults` — when the key is
/// `"en"` we resolve via the `translations` table; otherwise the German key
/// is returned verbatim (German is the source language).
public func __t(_ key: String) -> String {
    let loc = UserDefaults.standard.string(forKey: "wimg_locale") ?? "de"
    if loc == "de" { return key }
    return translations[key] ?? key
}

/// Interpolated form. Used by macro expansions for `#L("\(x) Foo")` → `__t("%@ Foo", x)`.
///
/// The macro always emits `%@` placeholders, but `%@` expects an
/// Objective-C object pointer at runtime. Swift's `CVarArg` conformance for
/// `Int`/`Double`/etc. hands raw bits, not a pointer — passing those to
/// `String(format:)` reads garbage as a pointer and crashes with
/// EXC_BAD_ACCESS. Coerce everything to `NSString` first so `%@` is always
/// satisfied regardless of the original Swift type.
public func __t(_ key: String, _ args: CVarArg...) -> String {
    let template = __t(key)
    let coerced: [CVarArg] = args.map { arg -> CVarArg in
        if let s = arg as? String { return s as NSString }
        if let ns = arg as? NSString { return ns }
        return String(describing: arg) as NSString
    }
    return String(format: template, arguments: coerced)
}
