import SwiftSyntax
import SwiftSyntaxMacros

/// Implementation of the `#L(...)` macro.
///
/// Takes a single string-literal argument, possibly with interpolation,
/// and expands to `__t(template, interpArgs...)`.
///
///     #L("Gesamtsaldo")
///       ↓ expands to
///     __t("Gesamtsaldo")
///
///     #L("\(count) Transaktionen")
///       ↓ expands to
///     __t("%@ Transaktionen", count)
///
/// `__t` is the runtime lookup function generated by `scripts/i18n-codegen.ts`
/// into the host target's `Translations.swift`.
public struct LocalizedMacro: ExpressionMacro {
    public static func expansion(
        of node: some FreestandingMacroExpansionSyntax,
        in context: some MacroExpansionContext
    ) throws -> ExprSyntax {
        guard let firstArg = node.arguments.first?.expression,
              let str = firstArg.as(StringLiteralExprSyntax.self)
        else {
            throw MacroError("#L requires a string literal as its first argument")
        }

        // No interpolation → simple lookup.
        if !hasInterpolation(str) {
            guard let key = staticString(str) else {
                throw MacroError("#L: could not extract string literal")
            }
            return "__t(\(literal: key))"
        }

        // Interpolation → build template + collect runtime args.
        var template = ""
        var interpArgs: [ExprSyntax] = []
        for segment in str.segments {
            if let lit = segment.as(StringSegmentSyntax.self) {
                template += lit.content.text
            } else if let interp = segment.as(ExpressionSegmentSyntax.self) {
                template += "%@"
                if let inner = interp.expressions.first?.expression {
                    interpArgs.append(inner)
                }
            }
        }

        // Build: __t("template", arg1, arg2, ...)
        var argList = "__t(\(literalQuoted(template))"
        for arg in interpArgs {
            argList += ", \(arg)"
        }
        argList += ")"
        return ExprSyntax(stringLiteral: argList)
    }

    // MARK: - helpers

    private static func hasInterpolation(_ str: StringLiteralExprSyntax) -> Bool {
        str.segments.contains { $0.is(ExpressionSegmentSyntax.self) }
    }

    private static func staticString(_ str: StringLiteralExprSyntax) -> String? {
        var out = ""
        for seg in str.segments {
            guard let lit = seg.as(StringSegmentSyntax.self) else { return nil }
            out += lit.content.text
        }
        return out
    }

    private static func literalQuoted(_ s: String) -> String {
        let escaped = s
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}

struct MacroError: Error, CustomStringConvertible {
    let description: String
    init(_ message: String) { self.description = message }
}
