/**
 * Generates Android string resources from the en.ts translation map.
 * Creates res/values-en/strings.xml for English translations.
 *
 * Usage: bun scripts/i18n-android.ts
 */
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { en } from "../wimg-web/src/lib/translations/en";

const outDir = "wimg-android/app/src/main/res/values-en";
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

// Also ensure default (German) strings exist
const defaultDir = "wimg-android/app/src/main/res/values";

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, '\\"')
    .replace(/'/g, "\\'")
    .replace(/\n/g, "\\n");
}

function toKey(s: string): string {
  // Convert German string to a valid Android resource key
  return s
    .toLowerCase()
    .replace(/[äöüß]/g, (c) => ({ ä: "ae", ö: "oe", ü: "ue", ß: "ss" })[c] || c)
    .replace(/[^a-z0-9]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .substring(0, 80);
}

// Generate both default (German) and English strings
const deEntries: string[] = [];
const enEntries: string[] = [];

for (const [de, enValue] of Object.entries(en)) {
  const key = toKey(de);
  if (!key) continue;
  deEntries.push(`    <string name="${key}">${escapeXml(de)}</string>`);
  enEntries.push(`    <string name="${key}">${escapeXml(enValue)}</string>`);
}

const header = `<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by scripts/i18n-android.ts — do not edit manually -->
<resources>`;
const footer = `</resources>`;

writeFileSync(`${outDir}/strings.xml`, `${header}\n${enEntries.join("\n")}\n${footer}\n`);
console.log(`Generated ${enEntries.length} English strings → ${outDir}/strings.xml`);

// Also generate German defaults
writeFileSync(`${defaultDir}/i18n_strings.xml`, `${header}\n${deEntries.join("\n")}\n${footer}\n`);
console.log(`Generated ${deEntries.length} German strings → ${defaultDir}/i18n_strings.xml`);
